apiVersion: v1
kind: ConfigMap
metadata:
    name: prytaneum-server-config
    namespace: production
    labels:
        app: prytaneum-server
data:
    HOST: 0.0.0.0
    NODE_ENV: production
    SERVER_PORT: '3002'
    GCP_PROJECT_ID: prytaneum-project
    PUB_SUB_PREFIX: projects/prytaneum-project/topics/
    REDIS_HOST: 10.169.113.211 # GCloud Memorystore Redis Instance IP
    REDIS_PORT: '6379'
    GCLOUD_ISSUE_GUIDES_STORAGE_BUCKET: prytaneum-issue-guides
    MODERATION_URL: http://10.112.10.190:5000/
