apiVersion: v1
kind: ConfigMap
metadata:
    name: moderation-algo-config
    namespace: production
    labels:
        app: moderation-algo
data:
    HOST: 0.0.0.0
    NODE_ENV: production
    GCP_PROJECT_ID: prytaneum-project
    REDIS_HOST: prod-redis-cluster.development.svc.cluster.local
    REDIS_PORT: '6379'
    REDIS_USERNAME: default
