name: Development Workflow

on:
    push:
        branches: [e2e-tester]

env:
    GKE_CLUSTER: prytaneum-dev-cluster
    GKE_ZONE: us-central1-a
    CLIENT_DEPLOYMENT: prytaneum-client
    SERVER_DEPLOYMENT: prytaneum-server
    CLIENT_IMAGE: prytaneum-client
    SERVER_IMAGE: prytaneum-server
    NAMESPACE: development
    GRAPHQL_URL: https://dev.prytaneum.io/graphql

jobs:
    linting:
        name: Linting
        runs-on: ubuntu-latest
        environment: development

        steps:
            - name: Setup
              uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: Yarn Install
              run: yarn install

            - name: Lint Project
              run: yarn workspaces foreach -p run lint

    typechecking:
        name: Type Check
        runs-on: ubuntu-latest
        environment: development

        steps:
            - name: Setup
              uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: Yarn Install
              run: yarn install

            - name: Prisma Generate
              run: yarn workspace @app/server generate

            - name: Type Check Project
              run: yarn workspaces foreach -p run typecheck

    e2e-testing:
        name: E2E Testing
        runs-on: ubuntu-latest
        environment: development
        timeout-minutes: 60

        steps:
            - name: Setup
              uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: Yarn Install
              run: yarn install

            - name: Prisma Generate
              run: yarn workspace @app/server generate

            - name: Install Playwright
              run: yarn workspace @app/client run playwright install --with-deps

            - name: Run Playwright tests
              run: yarn workspace @app/client run test:e2e:ci

            - uses: actions/upload-artifact@v2
              if: always()
              with:
                  name: allure-report
                  path: app/client/allure-report/
                  retention-days: 30

    build-client:
        name: Build Client
        runs-on: ubuntu-latest
        environment: development
        needs: [linting, e2e-testing, typechecking]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: dorny/paths-filter@v2
              id: changes
              with:
                  filters: |
                      client:
                        - 'app/client/**'

            # Configure Docker to use the gcloud command-line tool as a credential
            # helper for authentication
            - run: |-
                  gcloud --quiet auth configure-docker
            # Get the GKE credentials so we can deploy to the cluster
            - uses: google-github-actions/get-gke-credentials@v0.2.1
              with:
                  cluster_name: ${{ env.GKE_CLUSTER }}
                  location: ${{ env.GKE_ZONE }}
                  credentials: ${{ secrets.GKE_SA_KEY }}

            # Build the Client
            - name: Build Client
              if: steps.changes.outputs.client == 'true'
              run: |-
                  docker build \
                    -f ./docker/Dockerfile.client \
                    --tag "gcr.io/$PROJECT_ID/$CLIENT_IMAGE:$GITHUB_SHA" \
                    --build-arg GITHUB_SHA="$GITHUB_SHA" \
                    --build-arg GITHUB_REF="$GITHUB_REF" \
                    --build-arg GRAPHQL_URL="$GRAPHQL_URL" \
                    --build-arg DEPLOYMENT_ENV="development" \
                    .

    build-server:
        name: Build Server
        runs-on: ubuntu-latest
        environment: development
        needs: [linting, e2e-testing, typechecking]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: dorny/paths-filter@v2
              id: changes
              with:
                  filters: |
                      server:
                        - 'app/server/**'

            # Configure Docker to use the gcloud command-line tool as a credential
            # helper for authentication
            - run: |-
                  gcloud --quiet auth configure-docker
            # Get the GKE credentials so we can deploy to the cluster
            - uses: google-github-actions/get-gke-credentials@v0.2.1
              with:
                  cluster_name: ${{ env.GKE_CLUSTER }}
                  location: ${{ env.GKE_ZONE }}
                  credentials: ${{ secrets.GKE_SA_KEY }}

            # Build the Server
            - name: Build Server
              if: steps.changes.outputs.server == 'true'
              run: |-
                  docker build \
                    -f ./docker/Dockerfile.server \
                    --build-arg GITHUB_SHA="$GITHUB_SHA" \
                    --build-arg GITHUB_REF="$GITHUB_REF" \
                    .
